// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYLcrW3_AwzSEvloAJod1fWl65gIfD71I',
    appId: '1:153237815478:web:0371f37fe18abc8204a617',
    messagingSenderId: '153237815478',
    projectId: 'salahly-d4b8e',
    authDomain: 'salahly-d4b8e.firebaseapp.com',
    storageBucket: 'salahly-d4b8e.firebasestorage.app',
    measurementId: 'G-CVCSKJQDZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsfDjSe1yEFkHtZZPoiIH9vHoJ9zwc04Q',
    appId: '1:153237815478:android:8a314b809fa3562704a617',
    messagingSenderId: '153237815478',
    projectId: 'salahly-d4b8e',
    storageBucket: 'salahly-d4b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJs5LhiS6h4MR3Hb34vG33cmoJzP7TN3g',
    appId: '1:153237815478:ios:f64f02f4f935600e04a617',
    messagingSenderId: '153237815478',
    projectId: 'salahly-d4b8e',
    storageBucket: 'salahly-d4b8e.firebasestorage.app',
    iosBundleId: 'com.salahly.app',
  );
}
